SUI-Components/adevinta-spain-components

- components/ad/blockerExtensionDetector/src/index.js
Detele "remove method" isn't supported in IE11
> fix(ad/blockerExtensionDetector): deleted remove method

- components/link/basic/README.md
Fix on README sample to understand the pull request workflow
> docs(link/basic): update readme with fix on sample

- components/map/basic/src/leaflet/marker-manager.js
⚠️ I know this component has coupled code, but I have no time to refactor it.
> Add isContacted modifier class on realEstates that are contacted

- components/map/basic/src/leaflet/marker-manager.js
> Add isVisited modifier class on realEstates that are visited

- components/map/basic/src/leaflet/marker-manager.js
> Remove unnecessary code to Add isFavorited modifier class on realEstates that are favorited

- components/error/appBoundary/src/index.js
Move to dynamic import and remove deprecated require.ensure
> perf(error/appBoundary): remove deprecated require.ensure and use dynamic import

- components/list/bullet/src/index.scss
fix error when displaying illustrations on responsive desktop with margin right
> feat(list/bullet): fix error when displaying illustrations on responsive desktop device

- components/list/bullet/src/index.js
- components/list/bullet/src/index.scss
Adding smallFont prop so we can reuse this component in different pages.
> feat(list/bullet): add smallFont prop

- components/list/bullet/src/index.scss
during the refactor we have lost the medium illustration size.
so, fixing it.
> feat(list/bullet): icon size

- components/card/arrow/src/index.scss
adjust breakpoints in order to fit with UX design
> feat(card/arrow): adjust breakpoints

- components/layout/mediaQuery/src/index.js
check  this.containerResizeObserver before disconnect
> fix(layout/mediaQuery): fix when component will destroy

- components/topbar/composable/src/sui-topbar-composable-dropdown/index.js
[SCMI-27631](https://jira.scmspain.com/browse/SCMI-27631)
Add new `renderOnClick` prop
🔗[PR](https://github.schibsted.io/scmspain/frontend-fc--uilib-components/pull/712)
> feat(topbar/composable): add render on click prop

- components/dropdown/basic/src/index.js
Allow rel attribute for anchors.
> feat(dropdown/basic): allow rel attribute

- components/form/builder/README.md
- components/form/builder/src/components/button-group.js
- components/form/builder/src/components/input.js
- components/form/builder/src/components/select.js
- components/form/builder/src/components/text-area.js
- components/form/builder/src/index.js
- components/form/builder/src/validatorHoC/WithValidator.js
> Change in the way errors are displayed. Now it depends on a prop that will indicate if it should show them or not.
> feat(form/builder): update formbuilder show error management

- components/map/basic/src/index.js
- components/map/basic/src/leaflet/map.js
- components/map/basic/src/leaflet/shapes/Polygons.js
Add ShowLabels prop to render labels with the location name.
> Add ShowLabels prop to render labels with the location name

- components/map/basic/src/leaflet/shapes/Polygons.js
Remove a new search when clicking the current zone.
> fix(map/basic): remove a new search on click the current zone

- components/map/basic/src/index.js
- components/map/basic/src/leaflet/shapes/Polygons.js
> fix(map/basic): fix map basic hover problems with markers and polygons

- components/map/basic/src/index.js
- components/map/basic/src/leaflet/map.js
- components/map/basic/src/leaflet/marker-manager.js
SUI-Map refactoring removing FC coupled code.
> SUI-Map refactoring removing FC coupled code

- components/map/basic/src/leaflet/shapes/Polygons.js
Added corner case where mouse out was fired but the target element was still the same element
> feat(map/basic): fix hover on map

- components/collapsible/basic/src/index.js
Remove UNSAFE method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/schibsted-spain-components/136)
> [collapsible/basic]: Rewrite component

- components/perf/dynamicRendering/src/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/schibsted-spain-components/138)
> [perf/dynamicRendering] dynamicRendering MUST have a 1px margin bottom

- components/css/transition/src/animations-config.js
- components/css/transition/src/index.scss
- demo/css/transition/demo/index.js
Just added two new transitions:
- Fade in
- Fade out
> feat(css/transition): add new FADE_IN / FADE_OUT transitions

- components/perf/dynamicRendering/src/lazyContent.js
Make sure server and client render the same thing.
> fix(perf/dynamicRendering): avoid mismatch server/client

- components/cmp/ui/src/CmpUi/index.js
Users are complaining that the banner does not close after clicking on "seguir navegando"
> feat(cmp/ui): do not break on getvendors error

- components/map/basic/src/index.js
> feat(map/basic): change year

- demo/image/lazyLoad/playground
The API for the picsum.photos DEMO URLs was changed 🤷🏽‍♂️
> fix(Root): fixed the picsum.photos DEMO urls

- components/card/arrow/src/index.scss
- Add scss variable for box shadows on card/arrow component
> feat(card/arrow): add box shadow variables on card arrow component

- components/table/basic/src/index.js
- components/table/basic/src/index.scss
Added new prop `fullWith` & CSS class to render the table full width
> feat(table/basic): added new prop & CSS to render the table full width

- components/form/builder/src/reducer/rules.js
1 ms setTimeout to avoid IE 11 error - Access is denied - XMLHttpRequest
> fix(form/builder): 1 ms setTimeout to avoid IE 11 error - Access is denied - XMLHttpRequest

- components/topbar/composable/src/sui-topbar-composable-dropdown/index.js
[SCMI-35753](https://jira.scmspain.com/browse/SCMI-35753)
> feat(topbar/composable): add classname in memo

- components/form/autocompleted/src/index.js
> fix(form/autocompleted): remove this usage

- components/form/builder/src/Checkbox/index.scss
- components/form/builder/src/Select/Autosuggest/index.js
- components/form/builder/src/index.scss
- autosuggest field: if force value from outside sync state.
- checkbox field, uncomment styles.
> feat(form/builder): add reset state and force update from outside

- components/form/builder/src/Checkbox/index.js
- components/form/builder/src/FieldSet/index.js
- components/form/builder/src/Input/index.js
- components/form/builder/src/ProxyField/index.js
- components/form/builder/src/Select/Autosuggest/index.js
- components/form/builder/src/Select/Default/index.js
- components/form/builder/src/Select/index.js
- components/form/builder/src/Standard/Fields/FieldSet/index.js
- components/form/builder/src/Standard/Fields/Numeric/index.js
- components/form/builder/src/Standard/Fields/Picker/index.js
- components/form/builder/src/Standard/Fields/Text/index.js
- components/form/builder/src/Standard/index.js
- components/form/builder/src/TextArea/index.js
- components/form/builder/src/index.js
add onBlur callback to form/builder.
> feat(form/builder): super prop drilling onBlur callback

- components/image/slider/src/index.js
- components/image/slider/src/index.scss
> We need to center the image in case only one arrives in the array.
> fix(image/slider): single image center position

- components/form/builder/src/index.js
Export this method so everybody can modify any field of the JSON easily.
> feat(form/builder): export changeFieldById func

- components/form/builder/src/InlineButton/index.js
Pass props to Button component
> feat(form/builder): pass props to buttonInline's button component

- components/form/builder/package.json
- components/form/builder/src/Select/Autosuggest/index.js
- components/form/builder/src/Standard/index.js
- remove debugger
- accent insensitive
> feat(form/builder): autosuggest accent insensitive

- components/form/builder/src/reducer/rules.js
Form/builder remote rules fetching is crashing in IE. This pr fixes form/builder fetchRemoteFields xhr request.
> fix(form/builder): fetchRemoteFields xhr request

- components/cmp/modal/package.json
- components/cmp/modal/src/CmpModal/index.js
> [cmp/modal] Send custom event when disable all

- components/topbar/user/src/index.js
- demo/topbar/user/playground
`onToggle` prop will be executed each time user toggle topbar menu in mobile.
In motor we are going to use it in order to add some tagging.
> feat(topbar/user): onToggle prop

- components/form/builder/package.json
- components/form/builder/src/Input/index.js
- components/form/builder/src/Radio/index.js
- components/form/builder/src/Radio/index.scss
- components/form/builder/src/Select/Autosuggest/index.js
- components/form/builder/src/Select/Default/index.js
- components/form/builder/src/Standard/Fields/Picker/index.js
- components/form/builder/src/TextArea/index.js
- components/form/builder/src/index.scss
- add radio display
- use large select size.
> feat(form/builder): change some sizing

- components/form/builder/src/Radio/index.js
- components/form/builder/src/Standard/Fields/Picker/index.js
> feat(form/builder): add alert to radio button

- components/image/slider/src/index.js
- added new aria attribute `aria-selected` for better accessibility and testability 
- added `numOfSlides` as a new prop for `sliderOptions`
> feat(image/slider): improved a11y and new numOfSlides prop

- components/topbar/user/src/index.scss
https://github.com/SUI-Components/sui-components/pull/1056
> fix(topbar/user): button icon current color fix

- components/services/markdown/package.json
Upgrade `marked` from `0.4.0` to `0.8.2`
> feat(services/markdown): upgrade marked

- components/map/basic/src/leaflet/map.js
- components/map/basic/src/leaflet/shapes/Circle.js
- components/map/basic/src/leaflet/shapes/Polygons.js
- Add style capabilities to Circle Shape
- Disable fitbound styles if Circle must be render
> feat(map/basic): styles for circle shape

- components/list/bullet/README.md
> docs(list/bullet): improved ListBullet documentation

- components/list/bullet/src/index.js
> feat(list/bullet): export responsiveTypes

- components/form/builder/src/index.js
Prevent onChange multiple calls
> feat(form/builder): prevent onchange multiple calls

- components/cookie/banner/package.json
- components/cookie/banner/src/index.js
- components/cookie/banner/src/index.scss
- components/cookie/banner/src/settings.js
- demo/cookie/banner/playground
[SCMI-39279](https://jira.scmspain.com/browse/SCMI-39279)
> feat(cookie/banner): create new cookie banner

- components/form/builder/src/Select/Autosuggest/index.js
- components/form/builder/src/Select/Default/index.js
> feat(form/builder): add helptext to select fields

- components/form/builder/src/Radio/index.js
- components/form/builder/src/TextArea/index.js
- components/form/builder/src/index.scss
Add label manually into `Radio` type since there no label into `MoleculeRadioButtonGroup` component.
Add help to `Textarea`
> Feat/add label to radio & add help to textarea

- components/form/builder/src/Radio/index.js
- components/form/builder/src/index.scss
Fix hidden label for radio type.
> feat(form/builder): remove label radio button

- components/form/builder/src/Standard/index.js
- components/form/builder/src/reducer/fields.js
> fix(form/builder): validate  only visible fields

- components/form/builder/src/Standard/index.js
add empty errors to field if it is hidden
> fix(form/builder): add empty errors to field if it is hidden

- components/form/builder/src/index.js
export `fieldsNamesInOrderOfDefinition` function
> feat(form/builder): export fieldsNamesInOrderOfDefinition function

- components/list/bullet/src/bullet.js
- components/list/bullet/src/index.js
- demo/list/bullet/playground
As an SEO requirement, we need to define the heading in the bullet title.
> feat(list/bullet): added support Heading prop to improve the SEO

- components/tcf/ui/src/TCFContainer/TCFContainer.js
- components/tcf/ui/src/index.js
This PR updates the tcf ui component with the corresponding changes to work with the data structure that comes from boros library and with it's exposed methods.
https://jira.scmspain.com/browse/PSP-3199
The behavior has to be the same as before. 
This PR has to be done to master and merged after the [PR](https://github.com/SUI-Components/adevinta-spain-components/pull/247) for the update of the other tcf components. 
It had to be done in different PRs to avoid any issue with the publication of packages (because the ui component has as dependencies the firsLayer, secondLayer and services components)
I've done the pr through the branch of the other PR to be able to review only the corresponding changes.
> feat(tcf/ui): update with boros methods

- components/tcf/secondLayer/src/components/iconAccordion/index.js
- components/tcf/secondLayer/src/components/iconClose/index.js
- components/tcf/secondLayer/src/components/tcf-secondLayer-decision-group/index.js
- components/tcf/secondLayer/src/components/tcf-secondLayer-user-decision/index.js
- components/tcf/secondLayer/src/index.js
Improve performance of secondLayer component adding React.memo in some components.
In demo, try the React profiler in dev tools. 
Renderings without this PR: average of 13 ms
With this PR: 9 ms.
> feat(tcf/secondLayer): improve performance of rendering

- components/tcf/firstLayer/src/index.js
- components/tcf/firstLayer/src/index.scss
Style refactor for variant B of the experiment at Mobile First Layer
https://jira.scmspain.com/browse/PSP-3366
**Before**
**After**
> feat(tcf/firstLayer): refactor css for Variant B

- components/tcf/secondLayer/src/components/tcf-secondLayer-decision-group/index.scss
- components/tcf/secondLayer/src/components/tcf-secondLayer-user-decision/index.scss
- components/tcf/secondLayer/src/index.js
- components/tcf/secondLayer/src/index.scss
Solve all the design tasks to come out with the test in Fotocasa
https://jira.scmspain.com/browse/PSP-3374
**Before**
**After**
This PR is related to another one necessary to start the Fotocasa test:
https://github.mpi-internal.com/scmspain/frontend-fc--uilib-components/pull/1544
> feat(tcf/secondLayer): second layer refactor for MUST tasks

- components/tcf/firstLayer/src/index.scss
Added sass variable assignments to make it modifiable in the portal only by variables
> feat(tcf/firstLayer): change variables sass

- components/form/builder/src/Standard/index.js
add max and min validation for numeric inputs
> feat(form/builder): add max and min validation for numeric inputs

- components/tcf/ui/src/index.js
This PR enables the component tcf/ui to be used in ssr.
https://jira.scmspain.com/browse/PSP-3424
npm link and up ```npm run dev:ssr```
> fix(tcf/ui): check window to enable ssr

- components/tcf/ui/src/SecondLayer/index.js
Add link to vendors list in mobile
https://jira.scmspain.com/browse/PSP-3432
Have the Vendor List link also in Mobile
**Before**
**After**
> feat(tcf/ui): add link to vendors list in mobile

- components/form/builder/src/reducer/rules.js
use advgo.net insted of legacy domain schibsted.io
> fix(form/builder): use advgo.net instead of legacy domain schibsted.io

- components/thumbnail/list/package.json
- components/thumbnail/list/src/index.js
- components/thumbnail/list/src/index.scss
update reference to thumbnail-basic package
> fix(thumbnail/list): update package reference

- components/thumbnail/basic/src/index.scss
https://jira.scmspain.com/browse/PI-32651
> feat(thumbnail/basic): fix min height logos

- components/tcf/ui/src/FirstLayer/index.js
- components/tcf/ui/src/TCFContainer/TCFContainer.js
- components/tcf/ui/src/index.js
- demo/tcf/ui/demo/index.js
Remove automatic acceptance when scroll and adopt modal behaviour .
No visual changes
Enjoy the demo
> feat(tcf/ui): remove code from test and use modal option

- components/tcf/services/src/domain/ConsentDraft.js
Create valid getter for load consent use case.
> fix(tcf/services): create valid node in load user consent use case

- components/react/hooks/README.md
- components/react/hooks/src/index.js
- components/react/hooks/src/useOnClickOutside/index.js
REACT/HOOKS
Add a new hook to handle call methods when click outside a component
The implementation is taken from: https://usehooks.com/useOnClickOutside
> feat(react/hooks): add useOnClickOutside React Hook

- components/form/builder/src/reducer/rules.js
We get a field with name “field” from which the new options are going to be obtained in the “responseInterceptor"
> feat(form/builder): add field to responseInterceptor request

- components/form/builder/package.json
- components/form/builder/src/Standard/Fields/Multipicker/index.js
> fix case error MultiPicker

- components/topbar/user/src/index.js
- package.json
> fix(topbar/user): fix cta design

- components/map/basic/src/index.js
- components/map/basic/src/leaflet/map.js
This PR:
- Updates the map center when it's changed (only works if `isSetViewEnabled` prop is set to `true`)
- Adds `onMapDrag` prop
> feat(map/basic): add pan and drag cb

- components/tcf/ui/src/FirstLayer/index.js
Add testid attribute for integration testing.
https://jira.scmspain.com/browse/PSP-3772
ISSUES CLOSED: PSP-3772
> feat(tcf/ui): add testid in accept all button

- components/tag/chip/src/index.js
Support title html attribute for tag chip
> feat(tag/chip): add title attribute to tag chip

- components/form/builder/src/index.js
send the field in the third argument of the transformation
> feat(form/builder): send the field in the third argument of the transformation

- components/dropdown/user/README.md
- components/dropdown/user/src/index.js
> fix(dropdown/user): fix notifications

- .github/workflows/node.js.yml
Use `run_number` as `run_id` will stay even for re-running jobs.
> chore(Root): use run_number instead run_id

- components/tcf/ui/src/FirstLayer/index.js
- components/tcf/ui/src/FirstLayer/index.scss
- components/tcf/ui/src/SecondLayer/index.js
- components/tcf/ui/src/SecondLayer/index.scss
Due to recent changes in molecule/modal(this [PR](https://github.com/SUI-Components/sui-components/pull/1343)) the approximation that we did to have footer stop working, causing these problems:
**Desktop**
**Mobile**
**Desktop**
You can use the demo
**Mobile**
**Desktop**
**Mobile**
**Desktop & tablet**
To simplify I remove scss that overrides some styles of other components. Some minor changes in appearance.
Almost no real changes in js, besides of the indentation
ISSUES CLOSED: PSP-3859
https://jira.scmspain.com/browse/PSP-3859
> fix(tcf/ui): fix modal layout because new footer feature

- CONTRIBUTING.md
- components/abtesting/hooks/jest-tests/experiment-core.test.js
- components/abtesting/toggle/jest-tests/index.test.js
- components/form/pta/src/test/index.test.js
- package.json
Fix the tests as we use react 17 in the studio now
> chore(Root): empty line

- components/topbar/composable/src/sui-topbar-composable-dropdown/sui-topbar-composable-dropdown.scss
https://jira.scmspain.com/browse/SCMI-56485
> feat(topbar/composable): fix overlapping modal

- components/react/hooks/README.md
- components/react/hooks/package.json
- components/react/hooks/src/index.js
- components/react/hooks/src/useCopyToClipboard/index.js
- components/react/hooks/src/useMountedState/index.js
- components/react/hooks/src/useSetState/index.js
- demo/react/hooks/demo/UseBooleanDemo.js
- demo/react/hooks/demo/UseCopyToClipboardDemo.js
- demo/react/hooks/demo/UseMountedStateDemo.js
- demo/react/hooks/demo/UseSetStateDemo.js
- demo/react/hooks/demo/index.js
- demo/react/hooks/playground
> feat(react/hooks): add useMountedState useSetState useCopyToClipboard hooks

- components/share/socialMediaButtonsGroup/src/index.js
> fix(share/socialMediaButtonsGroup): fix undefined string

- components/react/hooks/package.json
- components/react/hooks/src/useCopyToClipboard/clipboard-copy.js
- components/react/hooks/src/useCopyToClipboard/index.js
> fix(react/hooks): support older browsers without async/await support

- components/form/builder/src/Checkbox/index.js
- components/form/builder/src/FieldSet/index.js
- components/form/builder/src/Input/index.js
- components/form/builder/src/Multicheckbox/index.js
- components/form/builder/src/ProxyField/index.js
- components/form/builder/src/Select/Autosuggest/index.js
- components/form/builder/src/Select/Default/index.js
- components/form/builder/src/Select/index.js
- components/form/builder/src/Standard/Fields/FieldSet/index.js
- components/form/builder/src/Standard/Fields/Multicheckbox/index.js
- components/form/builder/src/Standard/Fields/Numeric/index.js
- components/form/builder/src/Standard/Fields/Picker/index.js
- components/form/builder/src/Standard/Fields/Text/index.js
- components/form/builder/src/TextArea/index.js
- components/form/builder/src/index.js
This PR:
- Add `onFocus` callback to `FormBuilder`
> feat(form/builder): add onFocus callback

- components/map/basic/src/leaflet/map.js
> feat(map/basic): add stop polygon method to drawing API

- components/tag/chip/src/index.js
> fix(tag/chip): fix lint

- components/map/basic/package.json
- components/map/basic/src/index.js
- components/map/basic/src/leaflet/map.js
Adding new props to simplify polygon drawing on map
> feat(map/basic): add simplify geoJson

- components/googleApiClient/loader/.gitignore
- components/googleApiClient/loader/.npmignore
- components/googleApiClient/loader/README.md
- components/googleApiClient/loader/package.json
- components/googleApiClient/loader/src/index.js
- components/googleApiClient/loader/src/index.scss
- components/googleApiClient/loader/test/index.js
- demo/googleApiClient/loader/playground
Load Google API Client Javascript library. https://github.com/google/google-api-javascript-client
Related to GoogleOneTap
> feat(googleApiClient/loader): add google-api-client-loader component

- components/card/arrow/demo/playground
- components/card/arrow/src/index.scss
Enhance component responsiveness
> feat(components/card/arrow): Enhance CardArrow styling

- components/dropdown/user/src/index.js
Manage onClick events from parent
> feat(components/dropdown/user): add onclick method

- components/topbar/user/src/index.js
- package.json
> Fix topbar user click noop

- components/form/builder/package.json
This PR updates input field version to latests one (only a small breaking change was made due atom input that IMO doesn't affect the form)
> feat(components/form/builder): update input field version

- components/form/builder/demo/formList.js
- components/form/builder/demo/formPTAMotor.js
- components/form/builder/demo/index.js
- components/form/builder/src/Select/Default/index.js
- components/form/builder/src/Standard/Fields/Multicheckbox/index.js
- components/form/builder/src/Standard/index.js
This `PR` adds a `dropdown` display to the `multipicker` type of field, ie:
> Feat Multipicker with Dropdown display

- components/form/builder/src/InlineButton/index.js
Adds the possibility of rendering a custom children
> feat(components/form/builder): inline button

- components/form/builder/src/index.js
> feat(components/form/builder): add applyEmptyFields prop

- components/form/builder/src/Checkbox/index.js
- components/form/builder/src/Switch/index.js
Improve switch and check boolean values, when empty string JSON.parse trigger an error
> feat(components/form/builder): improve switch and check boolean values

- components/topbar/user/src/index.js
Add new property to `navCTA` prop.
> feat(components/topbar/user): add new property to navCTA prop

- components/form/builder/src/Select/Default/index.js
pass description from data to the MoleculeSelectOption
> feat(components/form/builder): pass description from data MoleculeSelectOption

- components/ad/smartbanner/src/index.js
add logoNode prop for full customization (we need to add a custom anti-phishing logo).
> feat(components/ad/smartbanner): add logoNode prop for fully customization

- components/form/builder/src/Select/Default/index.js
**Changes**
Let pass children to the select component to render custom content
**Context**
In MA we need to pass some custom components related to the select
> feat(components/form/builder): allow to pass children to the Select component

- components/form/builder/src/InlineButton/index.js
(form/builder): adds display to innerProps
> feat(components/form/builder): adds display to innerProps

- components/dropdown/basic/src/index.scss
Use new variable recently created in sui-theme as `inherit` by default. In motor we need to overwrite it to semibold
> feat(components/dropdown/basic): add variable to modify font-weight

- components/form/builder/src/Stepper/index.js
Improve compatibility and readability from formbuilder stepper using custom event
> feat(components/form/builder): Improve formbuilder stepper using custom event

- components/topbar/user/src/index.js
> feat(components/topbar/user): make CTA icon optional

- components/card/arrow/src/index.scss
Add variables to CardArrow component font sizes
> feat(card/arrow): add variables to card arrow font sizes

- components/form/builder/src/index.js
Add autocompleted field info on changing values.
When `onChange` receives the next field value, `handlerChange` will be call with `true` value for `autocompletedField`, to add that info on `onChange`call.
It's not a breaking change. Just adds info.
We (motor) need to know if a field has been autocomplete, and which one.
> feat(components/form/builder): add autocompleted field info on changing values

- components/topbar/user/src/index.js
- components/topbar/user/src/index.scss
Changes in order to accept a BrandImage node as a logo, so we can avoid loading the logo as a CSS background.
> Feat topbar user brand image

- components/react/hooks/package.json
Just bump version for `components/react/hooks`
> feat(components/react/hooks): bump version

- components/form/builder/src/index.js
Prevent send autocompleted info on onChange if it has a falsy value.
> feat(components/form/builder): prevent send autocompleted info on onChange if it has a falsy value

- components/form/builder/src/Range/Default/index.js
improve joinInputValues function
> feat(components/form/builder): improve joinInputValues function

- components/form/builder/package.json
- components/form/builder/src/index.js
> feat(components/form/builder): update atom spinner version

- components/form/builder/src/Range/Default/index.js
- components/form/builder/src/Range/Default/index.scss
form/builder: update range values by renderer and add children
> feat(components/form/builder): update range values by renderer

- components/react/hooks/src/useOnScreen/index.js
- Update the PropType to useOnScreen hook
> fix(components/react/hooks): Update the useOnScreen PropTypes

- components/form/builder/src/PickerSlider/index.js
This PR add renderer function support to `PickerField`
> feat(components/form/builder): add renderer function

- components/map/google/.gitignore
- components/map/google/.npmignore
- components/map/google/README.md
- components/map/google/demo/context.js
- components/map/google/demo/index.js
- components/map/google/demo/index.scss
- components/map/google/demo/package.json
- components/map/google/package.json
- components/map/google/src/index.js
- components/map/google/src/index.scss
- components/map/google/test/index.test.js
Create Map Google base component
> feat(components/map/google): Create Map Google base component

- components/map/google/src/index.js
Add import and export from MapGoogleMarker in MapGoogle
> feat(components/map/google): Add MapGoogleMarker import and export in MapGoogle

- components/form/builder/src/FieldSet/index.js
- components/form/builder/src/FieldSet/index.scss
This PR add `renderer` support (custom props and component) to `FieldSet` form builder component
> feat(components/form/builder): add fieldset custom render

- components/form/builder/src/TextArea/index.js
**In this Pull Request**
Expose text area value in blur callback
> feat(components/form/builder): expose textarea value in blur callback

- components/link/basic/src/index.js
Pass event to the onClick function
> feat(components/link/basic): pass event to onClick function

- components/map/google/demo/articles/MapAddOnsArticle.js
- components/map/google/src/index.js
- components/map/google/src/infoWindow/index.js
add and export infoWindow component
> feat(components/map/google): add and export infoWindow component

- components/login/passwordReset/src/domain/index.js
- components/login/passwordReset/src/domain/password/Repositories/HTTPPasswordRepository.js
- components/login/passwordReset/src/domain/password/Repositories/PasswordRepository.js
- components/login/passwordReset/src/domain/password/Requests/ChangePasswordRequest.js
- components/login/passwordReset/src/domain/password/Requests/factory.js
- components/login/passwordReset/src/domain/password/Services/ChangePasswordService.js
- components/login/passwordReset/src/domain/password/Services/factory.js
- components/login/passwordReset/src/domain/password/UseCases/ChangePasswordUseCase.js
- components/login/passwordReset/src/domain/password/UseCases/factory.js
- components/login/passwordReset/src/domain/test/password/ChangePasswordUseCaseSpec.js
- components/login/passwordReset/src/domain/test/password/index.js
Add an additional endpoint to finish password change process.
> feat(components/login/passwordReset): Add new endpoint to finish password change process

- components/login/passwordReset/src/components/Form/PasswordChangeForm.js
- components/login/passwordReset/src/components/Form/PasswordResetForm.js
- components/login/passwordReset/src/components/Input/ButtonWrapper.js
- components/login/passwordReset/src/components/Input/LoginButton.js
- components/login/passwordReset/src/components/Input/SubmitButton.js
Implementing password reset cross component.
Apply a small refactor to reuse common code in buttons.
> feat(components/login/passwordReset): Apply small component refactoring in buttons

- components/login/passwordReset/src/domain/index.js
- components/login/passwordReset/src/domain/password/Errors/EmptyPasswordError.js
- components/login/passwordReset/src/domain/password/Errors/InvalidPasswordError.js
- components/login/passwordReset/src/domain/password/Errors/factory.js
- components/login/passwordReset/src/domain/password/Requests/ChangePasswordRequest.js
- components/login/passwordReset/src/domain/password/Requests/factory.js
- components/login/passwordReset/src/domain/password/UseCases/ChangePasswordUseCase.js
- components/login/passwordReset/src/domain/password/UseCases/ValidatePasswordUseCase.js
- components/login/passwordReset/src/domain/password/UseCases/factory.js
- components/login/passwordReset/src/domain/test/password/ValidatePasswordUseCaseSpec.js
- components/login/passwordReset/src/domain/test/password/index.js
Add use case to validate passwords
> feat(components/login/passwordReset): Add use case to validate passwords

- components/login/passwordReset/src/components/Form/PasswordChangeForm.js
- components/login/passwordReset/src/components/Form/PasswordResetForm.js
- components/login/passwordReset/src/hooks/components/usePasswordChangeFormState.js
- components/login/passwordReset/src/hooks/components/usePasswordResetFormState.js
- components/login/passwordReset/src/literals/es-ES.js
Password reset cross-component
Improve error management to avoid re-renders and ensure all cases behave as expected.
Add repeat password validation.
> feat(components/login/passwordReset): Improve error management

- components/login/passwordReset/src/components/Form/PasswordResetForm.js
- components/login/passwordReset/src/hooks/components/usePasswordResetFormState.js
Implementing the password reset cross component
* Improve UX in reset password forms, changing when errors are validated. Now errors are validated when the submit button is pressed, instead of each time the email field is modified.
> feat(components/login/passwordReset): Improve UX in error handling

- components/login/passwordReset/src/components/Form/PasswordChangeForm.js
- components/login/passwordReset/src/components/Form/PasswordResetForm.js
Apply small adjustments in how errors are managed in order to improve user UX in reset password component.
> feat(components/login/passwordReset): Improve UX in error management

- components/login/header/README.md
Improve the sample code in the readme
> docs(components/login/header): improve the LoginHeader readme

- components/form/builder/src/Select/Default/index.js
A `form/builder` field with a `hidden` rule being applied was causing our select component to throw an error. 
````
react-dom.development.js?04cf:15050 Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
at renderWithHooks (react-dom.development.js?04cf:15050:1)
at updateFunctionComponent (react-dom.development.js?04cf:17356:1)
at beginWork (react-dom.development.js?04cf:19063:1)
at HTMLUnknownElement.callCallback (react-dom.development.js?04cf:3945:1)
at Object.invokeGuardedCallbackDev (react-dom.development.js?04cf:3994:1)
at invokeGuardedCallback (react-dom.development.js?04cf:4056:1)
at beginWork$1 (react-dom.development.js?04cf:23964:1)
at performUnitOfWork (react-dom.development.js?04cf:22776:1)
at workLoopSync …
```
> fix(components/form/builder): prevent race condition with hooks 

- components/form/builder/package.json
In CNET PRO, the vehicle form was not usable enought as it was not operable with key shortcuts. The main issue was that the tab key was not being properly recognized, and the user was not able to navigate between fields and select their value just by tabulating and selecting values.
1. Update some dependencies required to make the tab key to work.
**Co-author**
/w @davidmartin84
> feat(components/form/builder): Update dependencies

- components/login/passwordReset/src/components/Input/LoginButton.js
- fix(components/login/passwordReset): fix login session link
- fix(components/login/passwordReset): fix prop to the link
> XCOMP 8799 fix/login session link

- components/topbar/user/src/index.js
Pass linkfactory prop to CTA button to enable SPA navigation.
> feat(components/topbar/user): pass linkfactory prop to CTA button

- components/form/select/src/index.js
**ℹ️ TASK**: [SCMI-50332](https://jira.ets.mpi-internal.com/browse/SCMI-50332)
Add support for aria-label in form select.
> 🔍  feat(components/form/select): add support for aria label

- components/topbar/user/package.json
- components/topbar/user/src/index.js
BREAKING CHANGES:
Hide user badge
> feat(components/topbar/user): Hide user badge

- components/dropdown/user/package.json
- components/dropdown/user/src/index.js
BREAKING CHANGES:
Apply true small badge by default
> feat(components/dropdown/user): Apply true small badge by default

- components/react/hooks/src/useControlledState/index.js
> fix(components/react/hooks): don't need to store the state when controlled outside

- components/services/markdown/package.json
- components/services/markdown/src/index.js
- components/services/markdown/test/index.test.js
Update marked version to fix vulnerability
> Feature: Update marked version

- components/tool/taskManager/package.json
- components/tool/taskManager/src/domain/config.js
- components/tool/taskManager/src/index.js
- components/tool/taskManager/src/index.scss
> feat(components/tool/taskManager): update layout styles taskManager

- components/tool/taskManager/src/hooks/useState.js
Add additional methods to retrieve the status of in progress tasks.
This is a WIP. Most logic from this methods will be moved to the component's domain layer.
> feat(components/tool/taskManager): Add new getters to retrieve status

- components/tool/taskManager/src/hooks/useState.js
Add a function to count visible tasks, regardless of their status.
> feat(components/tool/taskManager): Add function to count visible tasks

- components/tool/taskManager/src/hooks/useDomainEventSubscriptions.js
- components/tool/taskManager/src/hooks/useState.js
Execute the onAllTasksComplete event only when visible tasks have been completed, ignoring non-visible tasks.
> feat(components/tool/taskManager): Avoid noticing non-visible tasks

- components/tool/app/bin/commands/addBiometricConfig.js
- components/tool/app/bin/commands/init.js
- components/tool/app/bin/infrastructure/utils.js
- components/tool/app/package.json
Add a small script to auto-config biometric permissions both for ios and android
> feat(components/tool/app): Auto-configure biometric permissions

- components/perf/dynamicRendering/src/index.js
This PR fixes a CLS issue in the `PerfDynamicRendering`
> feat(components/perf/dynamicRendering): remove use state

- components/tool/app/package.json
- components/tool/app/src/index.js
- components/tool/app/src/liveUpdates.js
Add capgo live update plugin to the available wrapped API.
> feat(components/tool/app): Add capgo live updates to the wrapped API

- components/tool/app/bin/commands/init.js
- components/tool/app/bin/commands/remove.js
- components/tool/app/package.json
- components/tool/app/src/core.js
Adding capacitor app to sui-app
> feat(components/tool/app): Add capacitor app to sui-app

- components/tool/app/src/core.js
Adding more required libs to sui-app to avoid directly consuming them
> feat(components/tool/app): Add Http client to sui-app

- components/form/builder/src/index.js
Fix Form Builder state when **React 18**.
With React 18 new **batch rendering**, when the component set the state fields with initial fields at mount, **only update the last field** because of the process read a ref instead the updated state in each iteration.
Before it, in some cases, you could find that a form works well, but it's happening when is applying rules at the first render.
**BEFORE:**
**AFTER:**
> feat(components/form/builder): Fix Form Builder init state when React 18

- components/topbar/user/src/index.js
Add common a11y attributes and new prop to customise aria-label.
> A11Y Update menu status and accessibility attrs

- components/form/builder/package.json
- components/form/builder/src/Select/Default/index.js
- package-lock.json
Upgrade molecule select field version on form builder component.
This PR will release a new **MAJOR VERSION** of form builder, although there are no breaking changes, but devs should upgrade to the new version of the form builder **AT THE SAME** time they upgrade the SUI Molecule Select Field && Molecule Select to v2, to avoid breaking some styles.
> feat(components/form/builder): upgrade molecule select version

- package-lock.json
> feat(Root): update deps

- components/form/builder/package.json
- components/form/builder/src/Switch/index.js
- package-lock.json
New version with updated s-ui/atom-switch.
Props of this component are different:
- `type` is now `design`
> Feature/form builder  upgrade atom switch

- components/dropdown/basic/src/index.js
- components/dropdown/basic/src/index.scss
- Change header tag to label
- Replace divs for spans in button's content
> fix(components/dropdown/basic): Change header tag to label

- components/dropdown/basic/src/index.js
Jira: https://jira.ets.mpi-internal.com/browse/MTR-96807
- Add aria-expanded attribute to indicate dropdown state
- Add aria-haspopup attribute for menu announcement
- Add aria-controls with unique ID to associate button with dropdown content
- Generate dynamic ID from button text for dropdown menu
> feat(components/dropdown/basic): add ARIA attributes for improved accessibility

- components/dropdown/basic/demo/playground
- components/dropdown/basic/src/index.js
Update regex to match all occurrences
> feat(components/dropdown/basic): Update replace

- components/dropdown/user/package.json
- components/dropdown/user/src/index.js
- components/dropdown/user/src/index.scss
- components/topbar/user/src/index.js
- package-lock.json
This PR implements accessibility improvements for the `topbar/user` and `dropdown/user` components, focusing on better screen reader support to enhance the user experience for people using assistive technologies.
Up until now, the notification badges were not a11y-friendly. This `PR` adds hidden text to help screen readers give all context to users. This hidden text could be something like `3 notifications` or anything that gives similar information to the visually impaired and the non-visually impaired user.
- Added `accessibleBadgeLabel` prop for `navUser`
- Added `accessibleBadgeLabel` prop for `navUser.menu[]`
- Use of VisuallyHidden component
- Handle `accessibleBadgeLabel` prop to show: assistive technology friendly text next to user name and next to menu items when there are …
> Accessibility Improvements for TopbarUser and DropdownUser Components

- components/form/builder/src/Switch/index.js
Replace the switch component color from NEUTRAL to PRIMARY.
> feat(components/form/builder): modify switch component color prop
