SUI-Components/adevinta-spain-components

components/cmp/modal/src/index.js, demo/cmp/modal/playground
- Add a new way to open the modal so monolithic applications without access to passing props to the component could use adding an click event to any HTML element to open it so do the usage of the component in a widget seamless.
=> feat(cmp/modal): add a prop to pass to the component an element and open the modal on clicking it

components/map/basic/src/leaflet/marker-manager.js
=> feat(map/basic): add propertyId on markers

.travis.yml, components/modal/basic/src/index.js
This #PR fixes problems when the component get unmounted and it left the className `is-modal-open` in the class of the body leading to bugs.
Also, the logic when it received props in order to update the open flag was wrong.
=> fix(modal/basic): fix behaviour of modal when unmount and updating open prop

components/map/basic/src/index.js, components/map/basic/src/leaflet/layer-manager.js
This PR will allow passing by props the text we want to show at the bottom-right side of the leaflet map.
This property is called `attribution`, and you can see its documentation from leaflet in the following link:
https://leafletjs.com/reference-1.3.4.html#control-attribution
=> feat(map/basic): allow customise attribution text displayed at the bottom right of map.

components/cmp/modal/src/index.scss
In the IE browser the body of the modal has no height. Giving a minimum height we ensure it's shown
correctly.
I decided `50 vh` just because in case the content of the `inner modal` does not height a lot, it will not look weird.
ISSUES CLOSED: #26
=> fix(cmp/modal): fix height of the innerMmodal in IE

components/layout/mediaQuery/src/breakpoints.js
What does this PR do?
Added min screen breakpoint that is 0. Why? Because there are resolutions like iPhone X that are smaller than XS breakpoint (480). For example, if I have and IphoneX (hopefully.... XD), the screen width is 375 pixels, then XS would be false and this means that we aren't in mobile resolution.
There are two available solutions:
- The first one adds the breakpoint 0 to check XXS breakpoint if is greater that this resolution would be mobile. To me would be more understandable. 
- The second solution could be where we are using this component do: (!XS) also would mean that we are on screen mobile resolution.
I did this PR because I prefer this solution (to me is more understandable) but I would like to know your opinion about it!
Thanks, mates! 👍
=> fix(layout/mediaQuery): added min breakpoint

components/map/basic/src/index.js, components/map/basic/src/leaflet/constants/index.js, components/map/basic/src/leaflet/layer-manager.js, demo/map/basic/playground
According to HERE Maps documentation, **we need to pass an additional query param `lg` in the map tile's URL in order to request them in a foreign language**. By default, all maps are displayed in English.
Docs: https://developer.here.com/api-explorer/rest/map-tile/map-tile-language
If you see in FC Search page map view, it is all always displayed in English, regardless the language you select on the page.
In New Construction's web app, we need to display them in Spanish and French.
So in the end, I have added support to: Spanish, English, Catalan, French, German; keeping the default language as English in order to keep current behaviour.
=> feat(map/basic): allow customise the language of map tiles.

components/cmp/banner/src/CmpBanner/component.js, components/cmp/banner/src/CmpBanner/index.js
Load dynamically the banner and the modal, only when they are needed so they're not included in the bundle by default.
=> perf(cmp/banner): load dynamically packages to avoid putting them in the bundle if not needed

components/collapsible/basic/src/_settings.scss, components/collapsible/basic/src/index.scss
1. The label class has been defined as flex:1 so that it occupies 100% of the space left by the iconBox class, which is the one it shares container with.
2. The value of the whitespace style of the label has been defined as a variable, since in the engine we need to change it to the normal value so that the text jumps to a new line.
=> feat(collapsible/basic): fix collapsible-basic styles

components/form/select/src/index.js
This pull request changes the behaviour of dropdown box in fotocasa/detail/Report 
It forces user to select a reason for reporting a property, before this change 'Selecciona' was an option to submit. After this change it will be an invalid option to submit. 
Apart from this change, frontend-fc--uilib-components needs to be changed too
=> adding a required optional attribute for select

components/section/info/src/index.js, components/section/info/src/index.scss
When SectionInfo has no title it has unnecessary padding.
=> feat(section/info): Remove unnecessary padding

components/error/appBoundary/src/index.js
Add a way to silent the error in case the developer knows is an error not important. For example, when the error is caused for a well-known no compatibility with a specific browser version.
=> feat(error/appBoundary): add silent prop

components/form/builder/README.md, components/form/builder/package.json, components/form/builder/src/components/button-group.js, components/form/builder/src/components/input.js, components/form/builder/src/components/select.js, components/form/builder/src/components/text-area.js, components/form/builder/src/index.js, components/form/builder/src/index.scss, components/form/builder/src/validatorHoC/WithValidator.js
> Now, the component is no longer responsible for managing the submit of the form.
This is because for product needs, we are forced to add the login component and others with user data, between the form and the submit button.
For this reason, the management of errors, we must also perform in the wrapper component, to prevent the action of sending data if any field contains an error.
=> feat(form/builder): refactor submit action

components/abtesting/hooks/src/useExperiment/index.js, components/abtesting/optimizelyXExperiment/src/index.js
\* In order for both test and production environments to work with the new experiment context, we need to make sure that `createContext()` is "the same one". This is a temporary solution to fix tests, but we'll need a solution which probably involves moving the experiment context into an isolated package.
=> fix(abtesting/hooks): fix experiment context tests by conditionally loading absolute/relative import

components/script/loader/README.md, components/script/loader/package.json, components/script/loader/src/helper.js, components/script/loader/src/index.js, demo/script/loader/playground
Some scripts need to load styles in order to work properly, so let's add a `styles` prop and inject it in the document `head`.
EDIT:
besides that, I did a full component refactor:
- moving deprecated default proptypes to deconstruction default values
- converting class into function
- use hooks (useState, useMount, useEffect)
=> feat(script/loader): load styles

components/react/hooks/src/useLegacyState/index.js
Inner `useState` in `useLegacyState` produces a race condition if two `setLegacyState` are run very closely, so the previous update could be lost. This is not how the legacy `this.setState` method actually works.
After a few minutes taking a look at it with @midudev we solved this by passing a function to `useState` instead, so we ensure that the object we extend the state from will always be the most updated one.
=> fix(react/hooks): make sure legacy state hook extends the most updated state

components/section/info/src/index.js, components/section/info/src/index.scss, demo/section/info/playground
On the `section/info` component:
=> feat(section/info): add withoutBorder prop

components/cmp/ui/src/CmpUiBanner/index.js
fix demo warning:
```
main.js:41046 Warning: Failed prop type: Invalid prop `icon` supplied to `MoleculeNotification`, expected a ReactNode.
in MoleculeNotification (created by CmpBanner)
in CmpBanner (created by CmpUiContainer)
in Suspense (created by CmpUiContainer)
in div (created by CmpUiContainer)
in CmpUiContainer (created by CmpServices)
in CmpServices (created by CmpUi)
in CmpUi
in div
console.<computed> @ main.js:41046
main.js:41046 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
in span (created by MoleculeNotification)
in div (created by MoleculeNotification)
in div (created by MoleculeNotification)
in div (created by …
```
=> fix(cmp/ui): remove banner icon prop

components/cmp/ui/src/CmpUi/index.js
Fix bug that made notification not to close when modal is accepted.
=> fix(cmp/ui): close banner when modal is accepted

components/map/basic/src/index.js, components/map/basic/src/leaflet/map.js, components/map/basic/src/leaflet/shapes/Polygons.js
Show label only on children and brothers. Until now, we were showing the label for the current location too.
In this example, we removed "El Masnou" label and only show its children.
=> feat(map/basic): do not show label to our current location

components/modal/basic/src/index.js
- 🐛 classList: toggle() method's second argument [is not supported by IE 11](https://caniuse.com/#search=classlist%20toggle)
=> fix(modal/basic): classList.toggle second argument not supported by IE 11

components/cmp/modal/src/index.scss, components/cmp/ui/src/index.scss
Not really a feature nor a fix, but a style change in order to ensure that the text on the content of the banner is properly displayed (`text-align: left`).
=> feat(cmp/ui): set text-align: center to sui-CmpUi-content

components/topbar/user/.eslintrc, components/topbar/user/src/index.js
If one of the selectors received on `elementsToKeepScrollOnToggleMenu` prop is not already mounted it will throw an error and breaks the entire page rendering
Also I remove eslintrtc because it was created before sui-lint be configured.
See https://github.com/SUI-Components/schibsted-spain-components/issues/131
=> Hotfix js error on modify unmounted element

components/perf/dynamicRendering/package.json, components/perf/dynamicRendering/src/index.js, components/perf/dynamicRendering/src/lazyContent.js, package.json
Use `useNearScreen` own hook in order to simplify perf dynamic rendering implementation.
Also, it will have the `intersection-observer` in a single place, perfect to keep in sync the version and avoid installing more than once.
=> feat(perf/dynamicRendering): reuse hook for intersection observer and simplify code

components/abtesting/hooks/src/useExperimentCore/index.js, components/abtesting/hooks/test/experiment-core.test.js
The state-like data coming from `useExperiment` is ok in most cases, but sometimes you wanna run some code right when the activation happens. That's where an `onActivation` event is useful. It receives the updated experiment data as an argument.
- Add `onActivation` param to the core.
- Cover `onActivation` with a test.
A refactor of experiment tooling docs is pending. I'll soon include `onActivation` on it, not in this PR though.
=> feat(abtesting/hooks): add onActivation event param to useExperimentCore

components/gigya/globalEvents/src/index.js
Use a function instead a class in order to remove the componentWillMount life cycle and simplify the component.
=> feat(gigya/globalEvents): move class to function and remove componentWillMount usage

components/card/article/src/index.js
Our TagChip component (encapsulating AtomTag) passed as a prop to card/article accepts a type property that makes it use a different CSS class accordingly. Hence, we need card/article to pass down that prop.
=> feat(card/article): make card/article pass on type prop to TagChip

components/card/arrow/src/index.js, components/card/arrow/src/index.scss, demo/card/arrow/playground
- Refactor card/arrow component to allow optional elements like image and description
- Add border-radius scss variable with default value to 0
*Desktop*
---
*Mobile*
=> feat(card/arrow): refactor card arrow component allow optional elements

demo/table/basic/playground
Updated the demo component with the correct prop names
- `contentHead` 👉🏼 `head`
- `contentBody` 👉🏼 `body`
- `contentFoot` 👉🏼 `foot`
=> fix(Root): changed to correct prop name in demo component

components/tracking/view/src/index.js
- during e2e tests it is super messy to handle `disable-tealium` with the url queryParameters (for example checking the resulting url when a button is clicked in the app).
- So, this PR adds the possibility to handle the `disable-tealium` flag via sessionStorage.
=> feat(root): add session storage disable-tealium

components/image/slider/package.json, components/image/slider/src/index.js
Move image/slider from class to function.
👋 Remove lodash.clonedeep not needed.
=> perf(image/slider): move image/slider to function and stop using cloneDeep

components/form/builder/src/reducer/rules.js
Trying to fix IE 11 permission denied ajax request: add `request.withCredentials = true` and remove timeout
=> fix(form/builder): add request.withCredentials = true and remove timeout

components/react/hooks/src/useMount/index.js
Fix to allow cleaning effects on hook
Fix not to cheat the deps `[]` of React -> `// eslint-disable-line`
Test where I run tests to compare the two different `useMount`:
[https://codesandbox.io/s/test-usemount-k9y43](https://codesandbox.io/s/test-usemount-k9y43)
`<FirstContent />` uses the current `useMount` and when unmounted does not clean the effect while `<SecondContent />` using the corrected `useMount` does.
=> fix(react/hooks): fix useMount effect with clear effect

components/react/hooks/README.md, components/react/hooks/src/index.js, components/react/hooks/src/useMediaQuery/index.js, demo/react/hooks/demo/index.js
**useMediaQuery** Hook. We can use it combined with our vertical breakpoints in order to use browser mediaQueries (same as css) but in JS 😃 
It observes the document to detect when its media queries change, instead of polling the values periodically.
Support
=> feat(react/hooks): useMediaQuery hook

components/form/builder/src/FieldSet/index.js
At Carfactory, some rules will result in hiding `Fieldset`s , so we add that check before the `formBuilder` render a `Fieldset`
=> feat(form/builder): add check of hidden property on fieldset component

components/form/builder/src/Checkbox/index.js, components/form/builder/src/FieldSet/index.js, components/form/builder/src/InlineButton/index.js, components/form/builder/src/Input/index.js, components/form/builder/src/ProxyField/index.js, components/form/builder/src/Select/Autosuggest/index.js, components/form/builder/src/Select/Default/index.js, components/form/builder/src/Select/index.js, components/form/builder/src/Standard/Fields/FieldSet/index.js, components/form/builder/src/Standard/Fields/Numeric/index.js, components/form/builder/src/Standard/Fields/Picker/index.js, components/form/builder/src/Standard/Fields/Text/index.js, components/form/builder/src/Switch/index.js, components/form/builder/src/TextArea/index.js, components/form/builder/src/index.js, components/form/builder/src/prop-types/index.js
Added the possibility to set alert texts on fields.
With these changes, we only can set these alerts from outside the form, but it may be interesting to do something like constraints but with alerts, defining some rules to set alerts.
Here an example of checkbox with `alertText` :
=> feat(form/builder): add field alerts

components/form/builder/src/index.js
Just export `pickFieldById` so it can be used outside `form/Builder`
=> feat(form/builder): export pickFieldById from component

components/form/builder/src/Input/index.js, components/form/builder/src/Standard/index.js
If a field type `text` with `numeric` display is defined in JSON field, it will force the input to show numeric keyboards on mobile. Ie:
```
"fields":
[
{
"id":"cashPrice",
"type":"text",
"display":"numeric"
}
]
```
=> feat(form/builder): pass input mode prop to atom input

components/abtesting/optimizelyXExperiment/README.md, components/abtesting/optimizelyXExperiment/src/index.js
In order to avoid noisy warning messages regarding using <Fragment> for variations, we're creating a new `EmptyVariation` that renders nothing but avoid warnings like this:
=> feat(abtesting/optimizelyXExperiment): add EmptyVariation component

components/list/bullet/src/bullet.js, components/list/bullet/src/index.js, components/list/bullet/src/index.scss, demo/list/bullet/playground
This component has a responsive behavior and we need to add a new behavior for the new design, so we applied the necessary changes to get the new layout in the mobile version and maintain the compatibility, **the changes needs to update the component on Baller Landing** because we are changing the **BOOLEAN prop** `responsive`  to **STRING prop** `responsive='responsive'`
=> feat(list/bullet): apply changes to have responsive block & string

components/form/builder/src/index.js, components/form/builder/src/reducer/index.js, components/form/builder/src/reducer/rules.js
**Renamed interceptor props**
`urlInterceptor` to `requestInterceptor`
`requestInterceptor` to `responseInterceptor`
**Request config** (_with requestInterceptor_)
From the need in `coches` to make the requests with a `tenant` in the request headers to differentiate in `coches` and in `motos`, we apply this change to be able to fetch a configuration object (following the **Axios** pattern) and to be able to make the requests with headers if necessary.
=> feat(form/builder): request config & interceptor props rename

components/react/hooks/README.md, components/react/hooks/src/useMediaQuery/index.js
`useMediaQuery` is causing mismatches as the initial state of the hook could be different on server and client.
In order to fix this, instead using the initial value of the state, we're relying on the effect to change the state.
Also, we're adding a new feature to pass an object with options. In these options you could define the default value of the match, in order to do the same in the server and the client. By default it behaves equally as before.
=> fix(react/hooks): fix useMediaQuery mismatch

components/form/builder/src/index.js
When using version 2 of **FormBuilder** on the platform to test the **JSON** (workbench), an unexpected behavior has been observed, since it does not launch the **onChange** method at the expected time.
In one of the last commits, a duplicate call to the **onChange** method was removed, but it was found that the other one worked correctly, so the change was made.
=> fix(form/builder): fix onChange behaviour

components/form/builder/src/index.scss
Due to the need for **UX**, we need to define different margins than those proposed for the default **FormBuilder**.
With this change we give the possibility to `overwrite this variable in the theme `of each vertical
=> feat(form/builder): field side margins as default variable

components/form/builder/src/Checkbox/index.js, components/form/builder/src/FieldSet/index.js, components/form/builder/src/InlineButton/index.js, components/form/builder/src/Input/index.js, components/form/builder/src/ProxyField/index.js, components/form/builder/src/Radio/index.js, components/form/builder/src/Select/Autosuggest/index.js, components/form/builder/src/Select/Default/index.js, components/form/builder/src/Select/index.js, components/form/builder/src/Standard/Fields/FieldSet/index.js, components/form/builder/src/Standard/Fields/Numeric/index.js, components/form/builder/src/Standard/Fields/Picker/index.js, components/form/builder/src/Standard/Fields/Text/index.js, components/form/builder/src/Switch/index.js, components/form/builder/src/TextArea/index.js, components/form/builder/src/index.js
Add **children** prop, that should be a function (called renderer inside form builder) that receives two arguments: id and innerProps. 
If this function returns: 
- A `component` it will be rendered [instead](https://github.com/SUI-Components/adevinta-spain-components/pull/233/files#diff-5831da6776fc2aa1c60a4984599677d3R80) of the sui-component.
- A plain JS `object`, this object will be [passed as props of the sui-component](https://github.com/SUI-Components/adevinta-spain-components/pull/233/files#diff-5831da6776fc2aa1c60a4984599677d3R90).
Example:
```js
<FormBuilder
json={JSONBuilder}
onChange={fields => updateFields(fields)}
onBlur={onBlur}
errors={errors}
>
{({id, innerProps}) => {
const props = {
color: {
size: 'large'
}
}
return props[id]
}}
</FormBuilder>
```
In this example the …
=> feat(form/builder): customize sui components via JS

components/form/builder/src/Standard/index.js
`JSON.parse` breaks if argument is not parseable, so if it is 'true' resolve as a true and everything else resolve to false and avoid breaking.
=> fix(form/builder): avoid breaking if value is not 'true' or 'false'

components/abtesting/hooks/src/useExperimentCore/index.js, components/abtesting/optimizelyXExperiment/README.md
Now that we can give names to experiments, it's easy to provide extra methods of fake activation out of the code scope.
This way, UX or other roles can check variations whenever they like without the need of setting up and publishing the AB Test on Optimizely Panel, which is slower, cumbersome and wastes traffic from the plan.
Simply add the `forceExperiment` query param to the URL on the address bar, providing experiment name and variation you want to activate as a value:
```
?forceExperiment=<experiment-name>|<variation-name>
```
For example, an experiment whose name is `myexperiment` with a `biggerButton` variation would look like this:
```
?forceExperiment=myexperiment|biggerButton
```
Note that this gets stored into the session storage, so the variation will show up through the …
=> feat(abtesting/hooks): add forceExperiment browser query flag

components/form/builder/src/Standard/index.js, components/form/builder/src/index.js
Fixes a function name containing a typo. Keeps backwards compatibility.
=> fix(form/builder): fix typo on function and export

components/list/link/package.json, components/list/link/src/index.js, components/list/link/src/index.scss
Surprisingly, list link used the old version of link/basic. With this change we're using the latest compatible version.
So, I'm moving this in order to avoid installing two different packages for the same thing.
=> feat(list/link): use new @s-ui/react-link-basic

components/tcf/firstLayer/src/index.js
Change the order of actions, to execute the handleCloseModal before that the parent (tcf ui) unmounts this component.
Also comment with Adevinta information is been removed
As a result of https://jira.scmspain.com/browse/PSP-3325
The UI component flow works correctly. All necessary actions are done before the unmounting
There is no change in this components demo, but the UI demo can be checked and there shouldn't be any console error.
=> fix(tcf/firstLayer): do action before to parent unmount child

components/tcf/firstLayer/src/index.js, components/tcf/secondLayer/src/index.js
With current version, no `purpose` data is being saved, neither `specialFeatures` nor `legitimateInterests`.
This fix adds the data initialization and manipulation from the second layer.
* https://jira.scmspain.com/browse/PSP-3347
Data is populated and saved to the consent string
Can be tested in the demo, check the saved value with `window.__tcfapi('getTCData', 2, console.log)`
=> fix(tcf/secondLayer): save purpose and specialFeatures data

components/tcf/firstLayer/src/index.js
When we go from the first layer to any other layer, the scroll listener should not be registered.
> the scroll listener is intended to be used for users that keep scrolling down with the first layer opened so it'll apply a default consent, but if the user has interacted with the first layer opening the configuration, it has not sense to keep listening the scroll (and closing the modal if the user is scrolling out the modal)
* https://jira.scmspain.com/browse/PSP-3355
* when the first layer is mounted, the scroll listener is registered, and when is unmounted, the scroll listener is unregistered
tested in the local demo 
`HOST=local.schibsted.io npm run dev tcf/ui -- --link-package=components/tcf/firstLayer`
=> fix(tcf/firstLayer): remove scroll listener on unmount

components/tcf/secondLayer/src/components/tcf-secondLayer-vendors-user-decision/index.scss, components/tcf/secondLayer/src/index.scss
Style fixes to be able to start test in fc
https://jira.scmspain.com/browse/PSP-3378 that is a part of https://jira.scmspain.com/browse/PSP-3374
**Before**
**After**
##Review steps
Start the [server](https://github.mpi-internal.com/scmspain/frontend-fc--web-server) linking the necessary packages and forcing the Tcf component instead of the Cmp in the shared footer component.
`npm run dev -- --link-package=../frontend-fc--uilib-components/components/shared/tcf --link-package=../frontend-fc--uilib-components/components/shared/footer --link-package=../../adevinta-spain-components/components/tcf/ui --link-package=../../adevinta-spain-components/components/tcf/secondLayer`
=> fix(tcf/secondLayer): add color styling to spans inside sui buttons

components/thumbnail/basic/src/Thumbnail.js, components/thumbnail/basic/src/index.scss
added a new class to align vertically to the center when image is smaller than container
Current:
Expected:
=> feat(thumbnail/basic): add min-height variable and added a new component class

components/tcf/ui/src/FirstLayer/index.scss, components/tcf/ui/src/SecondLayer/index.scss
During the integration of TCF in IJ the background color of the modal header was the primary of IJ
During the integration in CN/MN the background color of the first layer was grey
Fix the color to white according UX specs
=> fix header color to white

components/tcf/ui/src/SecondLayer/components/tcf-secondLayer-decision-group/index.js, components/tcf/ui/src/SecondLayer/components/tcf-secondLayer-vendorList/index.js, components/tcf/ui/src/SecondLayer/index.js, components/tcf/ui/src/SecondLayer/settings.js
Allows users to select and deselect consent and legitimate interest separately.
If new user, clicks on "Configurar", all purposes are disabled, and select consent of 2 first vendors (by default, all(458) legitimate interest are enabled below)
will produce this consent string ```CO3nHsiO3nHsiCBAGAENAxCgAAAAAAAAAAiQABMDH2r_p-vt7Xx_fs--_2yPMav-95b2_YZwwvGWfeG5MvL_g8LX7GZXgr8ExIFDIwSXTlggIO2jjSuJoQA4ESqxJlmMSbGR5mlE1kiTS2NvbOsDD-3z-Lp_slM96fX3__937_v_778AAAAA.YAAAAAAAAAAA```
If new user, clicks on "Configurar", all purposes are disabled and deselect legitimate interest of 2 first vendors (by default, all consents are disabled and all(458) legitimate interest are enabled)
will produce this consent string  ```CO3nIbGO3nIbGCBAGAENAxCgAAAAAAAAAAiQAAAMfSn-n6-3tfH9-z77_bI8xq_73lvb9hnDC8ZZ94bky8v-Dwt …
```
=> allow to select and deselect consent and legitimate interest in vendors

components/tcf/ui/src/FirstLayer/index.scss, components/tcf/ui/src/SecondLayer/index.scss
Modify the TCF to remove styles only from Infojobs
https://jira.scmspain.com/browse/PSP-3471
Background color change should be applied only for Infojobs
The changes will be applied to the React component of Infojobs:
https://github.mpi-internal.com/scmspain/frontend-jobs--uilib-components/blob/14fa006f15702bf1bf5dcabb9a9450c235cfa032/components/ads/cmpUi/src/index.scss
=> feat(tcf/ui): modify the TCF to remove styles only from infojobs

components/tcf/ui/src/FirstLayer/index.scss
Currently the background of the First Layer of the CMP is seen in a gray tone, it must be modified to white according to design
https://jira.scmspain.com/browse/PSP-3475
**Before**
**After**
The capture is from Fotocasa, but the change will be for all portals
=> feat(tcf/ui): change background color first layer

components/form/captcha/src/index.js
On this PR:
- Added `size` prop to component props.
- Added `compact` and `normal` sizes to be exported.
=> feat(form/captcha): add sizes to form/captcha component and export sizes

components/image/slider/src/index.js
We're currently not dealing with `imageObjectFit` prop when passed within `sliderOptions` prop. This PR addresses that.
=> feat(image/slider): add imageObjectFit as prop for sliderOptions

components/tcf/ui/src/index.js, demo/tcf/ui/demo/index.js
Following the changes made in #316 , this adds the `reporter` parameter to the TCF UI to provide it to the TCF Services.
* https://jira.scmspain.com/browse/PSP-3594
* No behavioral changes.
* TCF integration can be configured with an external reporter which will be able to receive TCF signals to collect metrics and analyze TCF operations.
Sample added in the UI Demo with a `console.log` reporter
`npm run dev tcf/ui`
=> feat(tcf/ui): add tcf reporter

components/tcf/ui/src/SecondLayer/index.js
ISSUES CLOSED: PSP-3624
Due to legal changes, the user cannot click outside to dismiss vendors and purposes layer.
https://jira.scmspain.com/browse/PSP-3624
=> feat(tcf/ui): remove posibility of close if click outside on second layer

components/tcf/ui/package.json, components/tcf/ui/src/FirstLayer/index.js, components/tcf/ui/src/SecondLayer/index.js
Follows the `tcf/ui` major release from this change: https://github.com/SUI-Components/adevinta-spain-components/pull/319
This PR is an update to be applied after the services major release, that will:
- remove the "update the consent values logic" from the UI, as it has to be done in the services use cases
- the UI will apply the user changes to the services use cases and get the react components state synced using the services layer "consent draft" state, which will be calculated so the UI has no need to do the logic
* https://jira.scmspain.com/browse/PSP-3561
* no behavioral changes, the change is only a "responsability" change to the services layer
`npm run dev tcf/ui -- --link-package=/Users/alex.castells/projects/adit/adevinta-spain-components/components/tcf/services`
- cannot be …
=> feat(tcf/ui): update for tcf/services major release

components/tcf/services/src/application/service/LoadUserConsentUseCase.js, components/tcf/services/src/application/service/SaveUserConsentUseCase.js, components/tcf/services/src/application/service/UpdateConsentPurposeUseCase.js, components/tcf/services/src/application/service/UpdateConsentSpecialFeatureUseCase.js, components/tcf/services/src/application/service/UpdateConsentVendorUseCase.js, components/tcf/services/src/core/service/isBoolean.js, components/tcf/services/src/domain/ConsentDraft.js, components/tcf/services/src/index.js, components/tcf/services/src/infrastructure/reporter/eventReporter.js, components/tcf/services/src/infrastructure/tcf/TcfRepository.js, test/tcf/services/application/service/loadConsentDraftUseCase.test.js, test/tcf/services/application/service/loadUserConsentUseCase.test.js, test/tcf/services/application/service/saveUserConsentUseCase.test.js
Actually, vendors are automatically updated only taking care about the second layer, but the user may have selected its preferences about advertising vendors and if the user has selected them, we should not modify them no matter if the user changes its purpose preferences.
P.ex: this happens if I accept all vendors, and later I reject the purpose to "create an advertising profile" and I open again the vendors layer:
Also, the vendors automatic update is not taking care of the GVL purposes used by each vendor that can be checked in each vendors node of the GVL here https://vendorlist.consensu.org/v2/vendor-list.json 
So this PR also fixes that, by:
- applying automatic vendor acceptance/rejection taking care about the user's selection in the second layer on purposes and special features
- …
=> feat(tcf/services): improve vendors acceptance logic

components/tcf/ui/src/FirstLayer/index.scss, components/tcf/ui/src/SecondLayer/index.scss
Slightly change the TCF First and Second Layer styles to solve a bug in Iphone 8 v13
https://jira.scmspain.com/browse/PSP-3641
That the user has access to the footer buttons
**Before**
**After**
=> feat(tcf/ui): changes in the First layer of the TCF-ui

components/tcf/ui/src/FirstLayer/index.js
Remove forgotten characters in the return statement.
**Before**
**After**
=> fix(tcf/ui): remove forgotten characters

components/form/builder/package.json, components/form/builder/src/MultiPicker/index.js, components/form/builder/src/MultiPicker/index.scss, components/form/builder/src/ProxyField/index.js, components/form/builder/src/Standard/Fields/Multipicker/index.js, components/form/builder/src/Standard/index.js
Add display `multipicker` value.
Given a field like:
```js
export const householdsExtrasField = {
id: FIELD_KEYS.HOUSEHOLDS_EXTRAS,
type: 'multipicker',
label: 'Extras',
value: [],
datalist: [
{value: '1', text: 'Ascensor'},
{value: '2', text: 'Garaje'},
{value: '16', text: 'Terraza'},
{value: '32', text: 'Calefacción'},
{value: '64', text: 'Piscina'},
{value: '128', text: 'Jardin'},
{value: '4', text: 'Amueblado'},
{value: '8', text: 'Trastero'}
]
}
```
It will render:
=> feat(form/builder): add multipicker field

components/abtesting/hooks/src/useExperimentCore/index.js, components/abtesting/hooks/src/useExperimentCore/storage.js
This fix will make FC not to crash when cookieless when an experiment is configured.
=> fix(abtesting/hooks): use safe method to storage

components/form/builder/src/index.js, components/form/builder/src/reducer/fields.js
Add a new prop `useNativeFieldType`
- (default) If false returns all fields as string
- if true returns the native value of the field.
If we have a form with images and we console.log the fields returned when : `useNativeFieldType: false`
If we have a form with images and we console.log the fields returned when : `useNativeFieldType: true`
With this change we can receive fields that are non strings like the media field in the captures. It also applies to numbers, or other kind of fields.
It is NOT a breaking change
=> feat(form/builder): add new prop useNativeFieldType to form builder

components/image/slider/src/index.js
Add width and height attributes for slider images if image object has those keys.
=> fix(image/slider): enable width and height attributes

components/tcf/ui/src/index.js
Related to change in boros-tcf: https://github.com/scm-spain/boros-tcf/pull/52
This enables `Adobe Audience Manager` vendor to save its consent to the `borosTcf` cookie in order to allow faster reads on its consent to users who already has accepted or rejected (and so, have a tcf cookie)
https://jira.scmspain.com/browse/PSP-3719
now it will be possible to know if, p.ex. DMP is consented by:
```
const borosTcfCookie = // read the borosTcf cookie value
const decodedBorosTcf = JSON.parse(atob(borosTcfCookie))
const isDmpAccepted =
decodedBorosTcf.purpose.consents[1] &&
decodedBorosTcf.purpose.consents[10] && 
decodedBorosTcf.vendor.consents[565]
```
checked locally linking the boros-tcf branch under PR. https://github.com/scm-spain/boros-tcf/pull/52
=> feat(tcf/ui): add adobe as vendor to be saved in borostcf cookie

components/tcf/ui/src/FirstLayer/index.scss
Due not reserving height for logo the metric of Cumulative Shift Layout could be affected.
This PR reserve the height of the logo to present the jump in the header.
https://jira.scmspain.com/browse/PSP-3704
**Before**
**After**
|![Screenshot 2020-11-27 at 13 46 53](https://user-images.githubusercontent.com/45286922/100451938-81849e80-30b8-11eb-8b15-ffb581770069.png)
**Before**
**After**
=> feat(tcf/ui): reserve the space for logo to improve CSL

components/map/basic/src/index.js, components/topbar/user/src/index.js
In desktop, each re-render makes we unlock scroll. Unlock scroll makes a scrollTop. So each re-render we scrollTop
It is an issue for product
=> fix(topbar/user): prevent unlock scroll on desktop

components/form/captcha/src/index.js
Due to the need that we have in Motor to show in the DOM two instances of the FormCaptcha component, we must adapt the component to accept a unique identifier of the container where the Captcha will be injected, because otherwise, we are trying to inject two instances in the same node, which is not possible.
=> feat(form/captcha): prevent non rendering in multiples instances

components/image/lazyLoad/src/index.js, components/image/lazyLoad/src/index.scss, demo/image/lazyLoad/playground
Adds this backwards compatible prop `fitMode` to the image/lazyLoad component.
`fitMode` refers to the `object-fit` CSS property that will be used and can be one of the following: `contain`, `cover`, `fill`, `none`. Defaults to `default` which is of no real CSS use.
=> Feat: new fitMode prop for image/lazyLoad 

components/form/builder/src/reducer/fields.js, components/form/builder/src/reducer/rules.js
When fetching remote fields, url should be encoded properly:
- Query String should be encoded using encodeURIComponent
- URL should be encoded using encodeURI
=> fix(form/builder): Encode remote url

components/ad/smartbanner/package.json, components/card/article/package.json, components/card/basic/package.json, components/card/product/package.json, components/card/subscription/package.json, components/cmp/banner/package.json, components/cmp/services/package.json, components/cmp/ui/package.json, components/dropdown/basic/package.json, components/form/checkbox/package.json, components/form/checkboxesWithParent/package.json, components/form/rangeDatepicker/package.json, components/list/tagcloud/package.json, components/modal/basic/package.json, components/modal/gallery/package.json, components/tag/chip/package.json, components/tag/deletableList/package.json, components/tag/selectable/package.json
Alphabetically order dependencies in some packages where they weren't. This has been done by a `npm run phoenix` automatically.
=> chore(Root): auto order dependencies

components/react/hooks/src/useOnScreen/index.js
While getting the position of the element by your reference, return the initial state by param.
=> feat(react/hooks): add initial value to useOnScreen hook

components/react/hooks/src/useOnScreen/index.js, jest.config.js, package.json
This PR fixes an issue for old browser versions that don't support the `IntersectionObserver` API completely so the polyfill must be used (see [issue](https://github.com/w3c/IntersectionObserver/issues/211)).
The condition to check if it was supported was taken from the polyfill.
=> fix(react/hooks): polyfill support for old chrome devices

components/tcf/ui/src/SecondLayer/services/secondsToUserReadable.js, test/tcf/ui/SecondLayer/secondsToUserReadable.test.js
The IAB vendor list will use null instead of -100 to flag the vendors that doesn't store cookies. This PR adds an additional check when that value is displayed. 
https://jira.scmspain.com/browse/PSP-3839
=> Add null to tcf cookie max age display

components/form/builder/README.md, components/form/builder/src/index.js
make it async the onChange return callback. 
This is a breaking change, but since the change was added 2 days ago and nobody is using this callback, a major will not be released and we avoid having to increase the major in all the components that use the form/builder.
=> feat(form/builder): make it async the onChange return callback

components/form/builder/package.json
Due we need to pass an initial value in MA, we've to increase to the third major to get the latest update about to fix about internalValue and value sync.
=> chore(form/builder): increase major of @s-ui/react-molecule-textarea-field from 2 to 3

components/image/slider/src/index.js
Feature to be able to render a component as a card inside the image gallery itself.
This is already supported by **react-slidy**, but as we have implemented the component, we only allow to display images through an img tag.
=> feat(image/slider): be able to send custom images to react-slidy

components/react/hooks/src/useOnScreen/index.js
Adds new prop in order to be able to use a threshold to indicate at what percentage of the target's visibility the observer's callback should be executed. 
API: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
=> feat(react/hooks): adds new prop in order to be able to use threshold

components/ad/smartbanner/src/index.js, components/ad/smartbanner/src/index.scss
Trying to fix this jump as it increases CLS
=> feat(ad/smartbanner): set placeholder space while icons are loading

components/tag/chip/src/index.js
Fix to avoid preventing event propagation if no handler is passed to the component.
=> fix(tag/chip): fix condition handler

components/thumbnail/basic/src/index.scss
Change css to improve CLS and avoid change of height when logs are being loaded 
https://user-images.githubusercontent.com/12948042/140350892-e3a6c0f6-be4a-4aa8-a99b-a009139aa552.mov
=> feat(components/thumbnail/basic): Change css to improve CLS

components/card/article/src/index.scss
This change is made in the context of coches.net rebranding.
We need to change the default color of a card article comments elements (both the comments icon and the number of comments).
Until now, the color was always set to the default gray color and wasn't possible to change it because the token wasn't defined as a default property.
Fixes or or relates to #MTR-49354
**Before:**
**After:**
=> feat(components/card/article): Add the possibility of changing color of card article comments by turning $c-comments into a default value

components/form/builder/src/index.js, components/form/builder/src/reducer/index.js, components/form/builder/src/reducer/rules.js
This PR adds support to base api url (no breaking change).
- Now clients will be able to change the base api url based on the **environment**
=> add base url to form builder

components/topbar/user/src/index.scss
A scss token has been added to the topbar/user component, in order to make customizable the toggle icon color.
Before this change, the topbar icon color was always accent. Now it's accent by default, but can be changed from the app theme.
coches.net rebranding experiment
[x] New feature, not breaking change
=> feat(components/topbar/user): Add a scss token to topbar/user to make the icon color customizable from the app theme

components/card/article/src/index.scss
In coches.net, news cards (which use the card/article component from adevinta-spain-components) need to have rounded borders.
We achieved so by using an existing SCSS token. However, we detected that after applying border radius, due to how the card image is positioned, top corners are not visually rounded.
To fix this, we need to apply an overflow hidden attribute to card articles, to ensure that images inside do not overflow the limits of the parent element.
=> feat(components/card/article): Add overflow param to card article component

components/form/builder/src/Stepper/index.js
Formbuilder stepper is not working in Firefox, when pressing the buttons nothing happens.
To fix that, I'm replacing "outerText" by "InnerText" in formbuilder stepper onChange handler.
OuterText is not supported by Firefox:
InnerText has compatibility with all browsers:
=> fix(components/form/builder): Reemplace outerText by innerText in formbuilder stepper

components/form/builder/src/Select/Default/index.js
We want to add content before and after the `Select` component. We already had `children` as way to add a node before but now we want to add a node also after. To avoid breaking changes I came up with a `content` prop.
Let me know what you think 🙏🏻
=> feat(components/form/builder): Add content prop to select

components/form/builder/src/reducer/rules.js
In CNET PRO we are migrating some endpoints to PACT. Some of these endpoints are in charge of calculating possible field values for a form which uses this form builder.
In this scenario, if the request `withCredentials` option is enabled, a CORS error occurs. We think that the most feasible solution seems to optionally disable this option, as we don't need it for our requests.
Thanks to 💟  @xmurcia @davidmartin84  and @IgnacioND, who contributed during this issue investigation.
=> feat(components/form/builder): Parametrize the withCredentials request option

components/services/markdown/demo/index.js, components/services/markdown/demo/playground, components/services/markdown/src/index.js
On this PR we're adding a new prop `onLoad` that will allow us to know when the markup has been loaded.
It also returns `html` as the markup `html` content and `setHtml`, the setter function from `useState`.
A `useCase` for this new prop could be, for instance: 
- a markdown text with placeholders is loaded
- those placeholders need to be updated on the text within the component
=> Feat markdown service callback

components/react/hooks/jest-tests/useMediaQuery.test.js, components/react/hooks/package.json, components/react/hooks/src/useMediaQuery/index.js
The current behaviour of hook is that we always initialize [the state value `match`](https://github.com/SUI-Components/adevinta-spain-components/blob/master/components/react/hooks/src/useMediaQuery/index.js#L10) with [`defaultMatches` value](https://github.com/SUI-Components/adevinta-spain-components/blob/master/components/react/hooks/src/useMediaQuery/index.js#L6) and really we use `window.match` after render of the DOM by `useEffect`. That causes in client where `window.match` is supported a change of `match` value and renders of the two cases that are using the `match` value.
Example:
As you can see below in the images, console section, `Mobile` and `Desktop` components will be rendered.
Demo of example: https://codesandbox.io/s/great-forest-zd7syl?file=/src/App.js 
- Use …
=> Use matchMedia as default value when is supported

components/topbar/user/package.json, components/topbar/user/src/index.js
...and early return if not on client.
There's an ongoing server error caused by the use of `useLayoutEffect` on this component.
````
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
at TopbarUser (webpack:///../node_modules/@s-ui/react-topbar-user/lib/index.js?:44:36)
at div
at SharedTopbar (webpack:///../components/shared/topbar/lib/index.js?:23:524)
at Topbar (webpack:///./components/Topbar/index.js?:10:329)
at div
at div
at div
at AdvertisingRoadblock …
```
=> Feat topbar use isomorphic layout

components/link/basic/package.json, components/link/basic/src/index.js, components/link/basic/src/index.scss
Add prop to support hide link to crawlers in LinkBasic component.
The technique used is to use semantic `button` instead `a`. Documentation can be found here: 
[https://www.searchenginejournal.com/prg-pattern-the-new-nofollow/392862/#close](https://www.searchenginejournal.com/prg-pattern-the-new-nofollow/392862/#close)
=> Feat/scmi 75314/hidden links in link basic

components/react/hooks/src/useLocalStorage/index.js
This hook implements a listener that waits until the local storage is manually changed through the browser. When this happen, it triggers a function to set the new value to the state of the hook.
In a previous implementation of this hook, we noticed that if the value that we want to save in the local storage tends to be a boolean, the `newValue` property of the listener's event, is always going to be a `String`. So if we change manually the LS to false, the `newValue` is going to be `"false"`. With this, the new state instead of a boolean `false` would be `"false"` and can lead to confusion when checking the value in the code.
This can happen also with other JSON string types (Objects, numbers...)
To solve this, we suggest adding a parser function argument that can ensure the correct …
=> Fix: Parse localStorage event value if it's boolean

components/login/passwordReset/package.json, components/login/passwordReset/src/context.js, components/login/passwordReset/src/domain/config.js, components/login/passwordReset/src/domain/index.js
Add domain to the `login/passwordReset` component.
It will contain and manage all logic related with the password reset flow.
By initializing a single component and specifying some basic configuration props, and app will be able to load all the login interface in a fully-working way.
In order to make this component as similar to our apps as possible, we are adopting sui domain inside it, to design and implement all the logic.
=> feat(components/login/passwordReset): Add domain

components/login/passwordReset/package.json, components/login/passwordReset/src/context.js, components/login/passwordReset/src/domain/config.js, components/login/passwordReset/src/hooks/useI18n.js, components/login/passwordReset/src/hooks/useI18nInitializer.js, components/login/passwordReset/src/index.js, components/login/passwordReset/src/literals/es-ES.js, components/login/passwordReset/src/literals/index.js
`login/passwordReset` will have its own default translations, which could be partially (or totally) replaced by the app invoking the component, by passing their i18n translator.
This is still a PoC and we are working on it. We'll add tests to this part on following PRs before adding new features.
=> feat(components/login/passwordReset): Add extensible i18n to the component

components/login/passwordReset/package.json, components/login/passwordReset/src/domain/password/Repositories/HTTPPasswordRepository.js, components/login/passwordReset/src/domain/test/password/ResetPasswordUseCaseSpec.js
Mock the reset password endpoint and make the use case fully functional.
We'll use sui-mockmock to make the dev process more easy, because using the new sui-mock library may require to modify ci steps to ensure msw is properly executed during the test running.
=> feat(components/login/passwordReset): Mock endpoint with sui-mock

components/login/passwordReset/src/domain/password/Errors/PasswordError.js, components/login/passwordReset/src/domain/password/Errors/factory.js, components/login/passwordReset/src/domain/password/Repositories/HTTPPasswordRepository.js, components/login/passwordReset/src/domain/password/Repositories/factory.js, components/login/passwordReset/src/domain/test/password/ChangePasswordUseCaseSpec.js, components/login/passwordReset/src/domain/test/password/ResetPasswordUseCaseSpec.js
We're implementing the `login/passwordReset` component. This component will allow any web-app to render the password reset interface in a fully functional way, in order to adopt the cross login system ensuring the best developer experience possible.
Stop using standard errors and wrap them on more semantic error class.
=> feat(components/login/passwordReset): Add more semantic errors

components/login/passwordReset/package.json, components/login/passwordReset/src/components/Form/PasswordChangeForm.js, components/login/passwordReset/src/hooks/components/useDisplayExpiredTokenError.js, components/login/passwordReset/src/literals/es-ES.js
Implementation of a cross component to allow users to reset their password.
Display an error if the user accesses to a password change link with an expired token.
=> feat(components/login/passwordReset): Display an error if token is expired

components/form/builder/src/Select/Default/index.js
Pass leftAddon prop to moleculeSelect to show icons on cochesnet forms:
=> feat(components/form/builder): pass leftAddon prop

components/form/builder/src/index.js
In CNET PRO we need to set an internal state when we initialize a form with a specific set of initialValues.
Ideally, to ensure the form flow is totally completed, we need to execute the `onChange` method.
The `onInitFieldsLoadEnd` is great for us as it executes an event once the initial fields have been loaded.
The only thing we are missing from it, is to have the current form state passed as a param.
This PR introduces a small change to add a parameter to `onInitFieldsLoadEnd`. It should not affect to apps already using it, as it wasn't receiving any parameter until now.
=> feat(components/form/builder): Add fields status when calling to onInitFieldsLoadEnd

components/tool/taskManager/README.md, components/tool/taskManager/src/domain/shared/ValueObjects/DateSharedValueObject.js, components/tool/taskManager/src/domain/task/Entities/TaskEntity.js, components/tool/taskManager/src/domain/task/Entities/WorkTaskEntity.js, components/tool/taskManager/src/domain/task/Services/CancelWorkTaskService.js, components/tool/taskManager/src/domain/task/Services/FinishWorkTaskService.js, components/tool/taskManager/src/domain/task/ValueObjects/StatusTaskValueObject.js
This component provides a set of tools and methods to register and run async tasks. It is specially useful in situations where heavy tasks need to be executed, or when a task is composed by many differentiated steps or actions that could depend between them.
TaskManager not only offers an API to run these kind of jobs, but also provides a system and a user interface to manage them. TaskManager can take care of making some specific actions when a task is completed, cancelled, or when an error occurs. It can also take care of retrying a specific job a number of times, or log errors to a third-party logging system. 
Additionally, as each task needs to match the shape expected by the TaskManager API's, the usage of TaskManager enforces having a more structured task definition, which at the …
=> Add documentation to the TaskManager component

components/tool/taskManager/src/hooks/useState.js, components/tool/taskManager/src/index.js
Instead of returning a specific state object, which represents the state in some specific moment, expose a function which returns the latest state reference.
=> feat(components/tool/taskManager): Expose state reference and add method to get a specific task

components/tool/taskManager/src/hooks/useBeforeUnloadEffect.js, components/tool/taskManager/src/hooks/useState.js, components/tool/taskManager/src/index.js
When closing the browser window, if there are tasks still in progress, and the task manager has been configured to be visible to the user, a confirmation popup will be displayed asking for confirmation.
=> feat(components/tool/taskManager): Display an alert if there are in progress tasks and the window is

components/tool/taskManager/src/domain/shared/ValueObjects/IdSharedValueObject.js, components/tool/taskManager/src/domain/task/Entities/TaskEntity.js, components/tool/taskManager/src/domain/task/Entities/WorkTaskEntity.js, components/tool/taskManager/src/domain/task/Entities/factory.js, components/tool/taskManager/src/domain/task/Services/RunSimpleTaskService.js, components/tool/taskManager/src/domain/task/UseCases/RunSimpleTaskUseCase.js, components/tool/taskManager/src/domain/task/ValueObjects/WorkListTaskValueObject.js, components/tool/taskManager/src/domain/test/task/RunSimpleTaskUseCaseSpec.js, components/tool/taskManager/src/domain/test/task/RunTaskUseCaseSpec.js, components/tool/taskManager/src/hooks/useDevMode.js, components/tool/taskManager/src/index.js
This PR modifies the TaskManager tool, and adds the `isVisible` property to task works. `isVisible` is set to `false` by default.
When the `isVisible` prop is set to false, the work is not displayed on the UI. Additionally, if all work from a task is defined as not visible, the task itself is also not visible.
This feature will be used on CNET PRO, to control which kind of tasks can be viewed by the end user (only the video-related tasks will be visible from the begining).
We have also introduced a developer mode on the task manager, that is enabled when the user clicks consecutively 20 times on the component. When the dev mode is enabled, all tasks and works are visible, regardless of their `isVisible` prop value.
=> feat(components/tool/taskManager): Add a feature to mark work as visible or hide it on the UI

components/map/google/src/drawer/index.js, components/map/google/src/drawer/settings.js
Fix:
- Delete zoomControl from MAP_ITERATION_OPTIONS
- Clear all listeners in each useEffect execution to prevent draw in map when users cancel this action
=> Fix: Clean listeners GoogleMapsDrawer

components/tool/taskManager/src/domain/task/Repositories/LocalStateTaskRepository.js
Instead of adding new tasks to the bottom of the tasks queue, now they are added to the top.
This doesn't affect to task execution priority.
=> feat(components/tool/taskManager): Add new tasks to the top of the queue

components/perf/dynamicRendering/src/index.js, components/perf/dynamicRendering/src/index.scss
Add the CSS property `content-visibility` to improve the performance.
We want to reduce the rendering time to improve the INP.
[content-visibility: the new CSS property that boosts your rendering performance](https://web.dev/articles/content-visibility)
_[INP](https://web.dev/articles/inp) is a metric that evaluates a page's ability to be reliably responsive to user input. Responsiveness can be affected by any excessive amount of work that occurs on the main thread, including rendering work._
_Whenever you can reduce rendering work on any given page, you're giving the main thread an opportunity to respond to user inputs more quickly. This includes rendering work, and using the content-visiblity CSS property where appropriate can reduce rendering work—especially during startup, when most …
=> feat(components/perf/dynamicRendering): add content-visibility property

components/topbar/user/src/index.js, components/topbar/user/src/index.scss
Adding new props for the topbar:
- `navButton`: allows adding a navigation button to the left of the Brand Icon / Image / Text
- `showBrandIcon`: determines whether the Icon should be shown instead of the Brand Image / Text
- `title`: allows for injecting a node as a custom title
=> Add new props to topbar/user

components/perf/dynamicRendering/src/index.js
This PR fixes a hydration mismatch issue caused by `const isOnBrowser = typeof window !== 'undefined'` side-effect in render
=> fix(components/perf/dynamicRendering): hydration mismatch

components/perf/dynamicRendering/src/index.js, components/perf/dynamicRendering/src/index.scss
This PR improves The `PerfDynamicRendering` component to avoid CLS issues adding the same placeholder node
=> feat(components/perf/dynamicRendering): small improvements for cls

components/perf/dynamicRendering/src/index.scss
JIRA: https://jira.ets.mpi-internal.com/browse/SCMI-115243
Content visibility auto seems to do not reserve the height space in items that are above the current scroll position. So when we do a scroll up this items spam in height and that triggers CLS.
https://github.com/SUI-Components/adevinta-spain-components/assets/66824007/69be21c9-0685-4908-bc2a-c34ae2562474
=> fix(components/perf/dynamicRendering): remove content-visibility rule to avoid CLS problem

components/tool/app/bin/commands/addBiometricConfig.js, components/tool/app/src/core.js, components/tool/app/src/index.js
This PR adds a new wrapped method from the Capacitor's API, to know if an app is currently running on a native platform, and differentiate from normal web browsers.
It also fixes a bug when defining biometric permissions on android.
=> feat(components/tool/app): Add isNative method

components/tool/app/bin/commands/addLiveUpdate.js, components/tool/app/bin/commands/init.js
Forcing the usage of Capacitor 5 until capgo updates all their plugins to the version 6.
=> feat(components/tool/app): Always install capacitor 5 related plugins

components/map/google/package.json, components/map/google/src/drawer/index.js
**ℹ️ TASK**: [SCMI-122666](https://jira.ets.mpi-internal.com/browse/SCMI-122666)
Add new unfinishedDrawing function on google maps drawer
This function is necessary for detect when users draw on map but never finish the polygon (just do a click on the map or the polygon has less than 3 points)
=> Feat: Add new unfinished drawing function on google maps drawer

components/share/socialMediaButtonsGroup/src/config.js
**Problem:**
Sometimes, when we are sharing an ad through WhatsApp, seems like some links are not sharing the og:image meta tag on the message. Checking our code, we were using **https://wa.me/?text=** api and seems like is not fully compatible with open graph
**Solution:**
We could use **https://api.whatsapp.com/send?text=** api which is more compatible.
=> feat(components/share/socialMediaButtonsGroup): Change Whatsapp share url to improve open graph meta

components/form/builder/src/Checkbox/index.js, components/form/builder/src/InlineButton/index.js, components/form/builder/src/Input/index.js, components/form/builder/src/MultiButton/index.js, components/form/builder/src/Multicheckbox/index.js, components/form/builder/src/PickerSlider/index.js, components/form/builder/src/Radio/index.js, components/form/builder/src/Range/Default/index.js, components/form/builder/src/Select/Autosuggest/index.js, components/form/builder/src/Select/Default/index.js, components/form/builder/src/Stepper/index.js, components/form/builder/src/Switch/index.js, components/form/builder/src/TextArea/index.js
This PR addresses an accessibility issue reported during an audit.
Make all helpTexts, errorTexts, and alertTexts of every field type to be a paragraph element ( `<p>` ), replacing the current span element.
=> Feature/a11y  form builder  use paragraph on help error and alert field texts

components/form/builder/src/Select/Default/index.js, components/form/builder/src/Switch/index.js
Add screen-readable aria-label to select options. Currently, it is equal to the value (ids mainly), and with this PR, it can be set manually or equal to the `Select` text by default.
=> Feature/a11y  form builder  add screen readable aria label to select options

components/collapsible/basic/src/index.js, components/collapsible/basic/src/index.scss
The component was using non-semantic divs for interactive elements, which created significant accessibility issues.
This commit addresses these issues by:
- Converting the main trigger from a `<div>` to a semantic `<button>` to provide native keyboard interaction (Enter, Space) and screen reader support.
- Adding `aria-expanded` and `aria-controls` attributes to communicate the component's state to assistive technologies.
- Replacing inner `<div>` elements with `<span>`s to ensure valid HTML structure inside the button.
- Ensuring the collapsible panel is hidden with `display: none` when collapsed, removing it completely from the accessibility tree as intended.
Jira: https://jira.ets.mpi-internal.com/browse/MTR-96905
=> Improve accessibility of CollapsibleBasic component
